@extends('layouts.pdf-base')

@section('title', 'Payroll Export')

@section('content')
<div class="pdf-header">
    <div class="document-title">Payroll Export</div>
    <div class="document-info"><strong>Period:</strong> {{ $start_date }} to {{ $end_date }}</div>
    <div class="document-info"><strong>Company:</strong> {{ $company->name ?? 'Aeternitas' }}</div>
    <div class="document-info"><strong>Generated:</strong> {{ date('Y-m-d H:i:s') }}</div>
</div>

<table>
    <thead>
        <tr>
            <th>Employee ID</th>
            <th>Employee Name</th>
            <th>Basic Salary</th>
            <th>Overtime</th>
            <th>Allowances</th>
            <th>Deductions</th>
            <th>Net Pay</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach($payrolls as $payroll)
        <tr>
            <td>{{ $payroll->employee->employee_id ?? 'N/A' }}</td>
            <td>{{ $payroll->employee->full_name ?? 'Unknown' }}</td>
            <td class="text-right">₱{{ number_format($payroll->basic_salary, 2) }}</td>
            <td class="text-right">₱{{ number_format($payroll->overtime_pay ?? 0, 2) }}</td>
            <td class="text-right">₱{{ number_format($payroll->allowances ?? 0, 2) }}</td>
            <td class="text-right">₱{{ number_format($payroll->deductions ?? 0, 2) }}</td>
            <td class="text-right">₱{{ number_format($payroll->net_pay, 2) }}</td>
            <td>{{ ucfirst($payroll->status) }}</td>
        </tr>
        @endforeach
        
        <tr class="total-row">
            <td colspan="2">TOTALS</td>
            <td class="text-right">₱{{ number_format($payrolls->sum('basic_salary'), 2) }}</td>
            <td class="text-right">₱{{ number_format($payrolls->sum('overtime_pay'), 2) }}</td>
            <td class="text-right">₱{{ number_format($payrolls->sum('allowances'), 2) }}</td>
            <td class="text-right">₱{{ number_format($payrolls->sum('deductions'), 2) }}</td>
            <td class="text-right">₱{{ number_format($payrolls->sum('net_pay'), 2) }}</td>
            <td></td>
        </tr>
    </tbody>
</table>

<div class="pdf-footer">
    <p>Total Employees: {{ $payrolls->count() }}</p>
    <p>Generated by Aeternitas Payroll System</p>
</div>
@endsection