<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payslip - {{ $employee->full_name ?? 'Employee' }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; }
        .company-name { font-size: 24px; font-weight: bold; color: #333; }
        .payslip-title { font-size: 20px; color: #666; margin: 10px 0; }
        .info-section { margin: 20px 0; }
        .info-row { margin: 5px 0; }
        .table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        .table th, .table td { padding: 10px; border: 1px solid #ddd; text-align: left; }
        .table th { background-color: #f5f5f5; font-weight: bold; }
        .total-row { font-weight: bold; background-color: #f0f0f0; }
        .amount { text-align: right; }
        .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">{{ $company->name ?? 'Company' }}</div>
        <div class="payslip-title">PAYSLIP</div>
        <div>Period: {{ $payroll->pay_period_start }} to {{ $payroll->pay_period_end }}</div>
        <div>Generated: {{ $today }}</div>
    </div>
    
    <div class="info-section">
        <div class="info-row"><strong>Employee:</strong> {{ $employee->full_name ?? 'N/A' }}</div>
        <div class="info-row"><strong>Employee ID:</strong> {{ $employee->employee_id ?? 'N/A' }}</div>
        <div class="info-row"><strong>Department:</strong> {{ $employee->department->name ?? 'N/A' }}</div>
    </div>
    
    <table class="table">
        <thead>
            <tr>
                <th>Description</th>
                <th class="amount">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Basic Salary</td>
                <td class="amount">₱{{ number_format($payroll->basic_salary, 2) }}</td>
            </tr>
            @if($payroll->overtime_pay > 0)
            <tr>
                <td>Overtime Pay</td>
                <td class="amount">₱{{ number_format($payroll->overtime_pay, 2) }}</td>
            </tr>
            @endif
            @if($payroll->allowances > 0)
            <tr>
                <td>Allowances</td>
                <td class="amount">₱{{ number_format($payroll->allowances, 2) }}</td>
            </tr>
            @endif
            @if($payroll->bonuses > 0)
            <tr>
                <td>Bonuses</td>
                <td class="amount">₱{{ number_format($payroll->bonuses, 2) }}</td>
            </tr>
            @endif
            <tr class="total-row">
                <td>Total Earnings</td>
                <td class="amount">₱{{ number_format($payroll->gross_pay, 2) }}</td>
            </tr>
            
            @if($payroll->deductions > 0)
            <tr>
                <td>Deductions</td>
                <td class="amount">₱{{ number_format($payroll->deductions, 2) }}</td>
            </tr>
            @endif
            @if($payroll->tax_amount > 0)
            <tr>
                <td>Tax</td>
                <td class="amount">₱{{ number_format($payroll->tax_amount, 2) }}</td>
            </tr>
            @endif
            <tr class="total-row">
                <td>Total Deductions</td>
                <td class="amount">₱{{ number_format($payroll->deductions + $payroll->tax_amount, 2) }}</td>
            </tr>
        </tbody>
    </table>
    
    <div style="text-align: center; padding: 20px; border: 2px solid #000; margin: 30px 0;">
        <h2 style="margin: 0; color: #333;">NET PAY: ₱{{ number_format($payroll->net_pay, 2) }}</h2>
    </div>
    
    <div class="footer">
        <p>Generated by Payroll System</p>
        <p>This is an official document. Unauthorized distribution is prohibited.</p>
    </div>
</body>
</html>