<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Employee Documents Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .header h1 {
            color: #2d3748;
            margin-bottom: 5px;
        }
        .header p {
            color: #718096;
            margin: 2px 0;
        }
        .filters {
            background-color: #f7fafc;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .filters h3 {
            margin-top: 0;
            color: #2d3748;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #4a5568;
            color: white;
            padding: 10px;
            text-align: left;
            border: 1px solid #cbd5e0;
        }
        td {
            padding: 8px 10px;
            border: 1px solid #cbd5e0;
        }
        tr:nth-child(even) {
            background-color: #f7fafc;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #cbd5e0;
            text-align: center;
            color: #718096;
            font-size: 10px;
        }
        .total {
            margin-top: 20px;
            padding: 10px;
            background-color: #e6fffa;
            border-radius: 5px;
            text-align: right;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Employee Documents Report</h1>
        <p>Generated on: {{ $filters['export_date'] }}</p>
        <p>Total Employees: {{ $filters['total_employees'] }}</p>
    </div>
    
    <div class="filters">
        <h3>Filters Applied:</h3>
        <p><strong>Department:</strong> {{ $filters['department'] }}</p>
        <p><strong>Status:</strong> {{ $filters['status'] }}</p>
        <p><strong>Search Term:</strong> {{ $filters['search'] }}</p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Employee ID</th>
                <th>Full Name</th>
                <th>Department</th>
                <th>Position</th>
                <th>Status</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Salary</th>
                <th>Hire Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($employees as $employee)
            <tr>
                <td>{{ $employee['employee_id'] }}</td>
                <td>{{ $employee['full_name'] }}</td>
                <td>{{ $employee['department'] }}</td>
                <td>{{ $employee['position'] }}</td>
                <td>{{ $employee['status'] }}</td>
                <td>{{ $employee['email'] }}</td>
                <td>{{ $employee['phone'] }}</td>
                <td>{{ $employee['salary'] }}</td>
                <td>{{ $employee['hire_date'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="total">
        Total Records: {{ count($employees) }}
    </div>
    
    <div class="footer">
        <p>Generated by Aeternitas System • Confidential Document</p>
        <p>Page {{ $pdf->getPageNumber() }} of {{ $pdf->getPageCount() }}</p>
    </div>
</body>
</html>